kind: Secret
apiVersion: v1
metadata:
  name: secrect-without-annotation
type: Opaque
stringData:
  username: <path:argocd/data/{{ .Values.env }}#username>
  token: <path:argocd/data/global#globalToken>
