# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
serviceAccount:
  # Specifies whether a service account should be created
  create: true
env: development
